server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.236.128:3306/guli_pms
    username: root
    password: 123456
  redis: 192.168.236.128
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
